#pragma once

namespace ImGuiCLI
{

    public ref class ICON_FA
    {
    public:
        static property System::String^ NOTES_MEDICAL { System::String^ get(); }
        static property System::String^ CODE { System::String^ get(); }
        static property System::String^ COPY { System::String^ get(); }
        static property System::String^ CHEVRON_CIRCLE_RIGHT { System::String^ get(); }
        static property System::String^ CROSSHAIRS { System::String^ get(); }
        static property System::String^ EXTERNAL_LINK_SQUARE_ALT { System::String^ get(); }
        static property System::String^ HAND_LIZARD { System::String^ get(); }
        static property System::String^ CHESS_BISHOP { System::String^ get(); }
        static property System::String^ ANGLE_DOUBLE_LEFT { System::String^ get(); }
        static property System::String^ TH { System::String^ get(); }
        static property System::String^ ANGLE_LEFT { System::String^ get(); }
        static property System::String^ RECYCLE { System::String^ get(); }
        static property System::String^ SMILE { System::String^ get(); }
        static property System::String^ PIGGY_BANK { System::String^ get(); }
        static property System::String^ OUTDENT { System::String^ get(); }
		
		
        static property System::String^ FAX { System::String^ get(); }
        static property System::String^ CALENDAR_PLUS { System::String^ get(); }
        static property System::String^ LONG_ARROW_ALT_RIGHT { System::String^ get(); }
        static property System::String^ IMAGES { System::String^ get(); }
        static property System::String^ GAVEL { System::String^ get(); }
        static property System::String^ FIRE_EXTINGUISHER { System::String^ get(); }
        static property System::String^ VOLUME_UP { System::String^ get(); }
        static property System::String^ CLIPBOARD_LIST { System::String^ get(); }
        static property System::String^ CARET_UP { System::String^ get(); }
        static property System::String^ FILE_PDF { System::String^ get(); }
        static property System::String^ MAGIC { System::String^ get(); }
        static property System::String^ SEEDLING { System::String^ get(); }
        static property System::String^ LIST { System::String^ get(); }
        static property System::String^ UPLOAD { System::String^ get(); }
        static property System::String^ MAGNET { System::String^ get(); }
        static property System::String^ ADJUST { System::String^ get(); }
        static property System::String^ SUBWAY { System::String^ get(); }
        static property System::String^ HEADING { System::String^ get(); }
        static property System::String^ CHECK_CIRCLE { System::String^ get(); }
        static property System::String^ ARROW_DOWN { System::String^ get(); }
        static property System::String^ BICYCLE { System::String^ get(); }
        static property System::String^ SYNC { System::String^ get(); }
        static property System::String^ CROP { System::String^ get(); }
        static property System::String^ SIGN { System::String^ get(); }
        static property System::String^ ARROW_CIRCLE_DOWN { System::String^ get(); }
        static property System::String^ PAPER_PLANE { System::String^ get(); }
        static property System::String^ DOWNLOAD { System::String^ get(); }
        static property System::String^ VOLLEYBALL_BALL { System::String^ get(); }
        static property System::String^ RIBBON { System::String^ get(); }
        static property System::String^ CARET_DOWN { System::String^ get(); }
        static property System::String^ CHEVRON_LEFT { System::String^ get(); }
        static property System::String^ CARET_LEFT { System::String^ get(); }
        static property System::String^ CLOCK { System::String^ get(); }
        static property System::String^ SUN { System::String^ get(); }
        static property System::String^ CART_PLUS { System::String^ get(); }
        static property System::String^ CLIPBOARD { System::String^ get(); }
        static property System::String^ PHONE_SLASH { System::String^ get(); }
        static property System::String^ REPLY { System::String^ get(); }
        static property System::String^ HOURGLASS_HALF { System::String^ get(); }
        static property System::String^ LONG_ARROW_ALT_UP { System::String^ get(); }
        static property System::String^ GRADUATION_CAP { System::String^ get(); }
        static property System::String^ CHESS_KNIGHT { System::String^ get(); }
        static property System::String^ BURN { System::String^ get(); }
        static property System::String^ TAGS { System::String^ get(); }
        static property System::String^ FILE_ALT { System::String^ get(); }
        static property System::String^ MEH { System::String^ get(); }
        static property System::String^ PAUSE { System::String^ get(); }
        static property System::String^ BOX { System::String^ get(); }
        static property System::String^ DIAGNOSES { System::String^ get(); }
        static property System::String^ FILE_IMAGE { System::String^ get(); }
        static property System::String^ TV { System::String^ get(); }
        static property System::String^ ARROW_CIRCLE_RIGHT { System::String^ get(); }
        static property System::String^ CALENDAR_TIMES { System::String^ get(); }
        static property System::String^ TASKS { System::String^ get(); }
        static property System::String^ GAMEPAD { System::String^ get(); }
        static property System::String^ QUOTE_LEFT { System::String^ get(); }
        static property System::String^ MOBILE_ALT { System::String^ get(); }
        static property System::String^ EYE_SLASH { System::String^ get(); }
        static property System::String^ REDO { System::String^ get(); }
        static property System::String^ CLOUD { System::String^ get(); }
        static property System::String^ HAND_HOLDING_USD { System::String^ get(); }
        static property System::String^ EYE { System::String^ get(); }
        static property System::String^ CERTIFICATE { System::String^ get(); }
        static property System::String^ BASEBALL_BALL { System::String^ get(); }
        static property System::String^ PASTE { System::String^ get(); }
        static property System::String^ HOSPITAL { System::String^ get(); }
        static property System::String^ CAMERA { System::String^ get(); }
        static property System::String^ MUSIC { System::String^ get(); }
        static property System::String^ PEN_SQUARE { System::String^ get(); }
        static property System::String^ BRIEFCASE_MEDICAL { System::String^ get(); }
        static property System::String^ SORT { System::String^ get(); }
        static property System::String^ PLUG { System::String^ get(); }
        static property System::String^ SHOPPING_CART { System::String^ get(); }
        static property System::String^ MOUSE_POINTER { System::String^ get(); }
        static property System::String^ ENVELOPE { System::String^ get(); }
        static property System::String^ WINDOW_RESTORE { System::String^ get(); }
        static property System::String^ PHONE { System::String^ get(); }
        static property System::String^ FLAG { System::String^ get(); }
        static property System::String^ TRAIN { System::String^ get(); }
        static property System::String^ BULLHORN { System::String^ get(); }
        static property System::String^ CLIPBOARD_CHECK { System::String^ get(); }
        static property System::String^ CIRCLE { System::String^ get(); }
        static property System::String^ DOLLY_FLATBED { System::String^ get(); }
        static property System::String^ ADDRESS_CARD { System::String^ get(); }
        static property System::String^ I_CURSOR { System::String^ get(); }
        static property System::String^ CAR { System::String^ get(); }
        static property System::String^ CARET_SQUARE_UP { System::String^ get(); }
        static property System::String^ PARAGRAPH { System::String^ get(); }
        static property System::String^ MALE { System::String^ get(); }
        static property System::String^ HISTORY { System::String^ get(); }
        static property System::String^ H_SQUARE { System::String^ get(); }
        static property System::String^ HEART { System::String^ get(); }
        static property System::String^ LOCK_OPEN { System::String^ get(); }
        static property System::String^ SEARCH_PLUS { System::String^ get(); }
        static property System::String^ LIFE_RING { System::String^ get(); }
        static property System::String^ LOCK { System::String^ get(); }
        static property System::String^ STEP_FORWARD { System::String^ get(); }
        static property System::String^ SHARE { System::String^ get(); }
        static property System::String^ TAG { System::String^ get(); }
        static property System::String^ ALIGN_JUSTIFY { System::String^ get(); }
        static property System::String^ CHEVRON_CIRCLE_DOWN { System::String^ get(); }
        static property System::String^ TICKET_ALT { System::String^ get(); }
        static property System::String^ BATTERY_THREE_QUARTERS { System::String^ get(); }
        static property System::String^ MAP { System::String^ get(); }
        static property System::String^ OBJECT_UNGROUP { System::String^ get(); }
        static property System::String^ BRIEFCASE { System::String^ get(); }
        static property System::String^ MARS_STROKE_V { System::String^ get(); }
        static property System::String^ CLONE { System::String^ get(); }
        static property System::String^ THERMOMETER_FULL { System::String^ get(); }
        static property System::String^ ID_CARD_ALT { System::String^ get(); }
        static property System::String^ CHECK_SQUARE { System::String^ get(); }
        static property System::String^ CHART_LINE { System::String^ get(); }
        static property System::String^ UNLINK { System::String^ get(); }
        static property System::String^ DOVE { System::String^ get(); }
        static property System::String^ ENVELOPE_OPEN { System::String^ get(); }
        static property System::String^ STEP_BACKWARD { System::String^ get(); }
        static property System::String^ WHEELCHAIR { System::String^ get(); }
        static property System::String^ MICROPHONE_SLASH { System::String^ get(); }
        static property System::String^ ANGLE_DOUBLE_UP { System::String^ get(); }
        static property System::String^ USER_PLUS { System::String^ get(); }
        static property System::String^ TRUCK { System::String^ get(); }
        static property System::String^ LEVEL_UP_ALT { System::String^ get(); }
        static property System::String^ FLASK { System::String^ get(); }
        static property System::String^ WON_SIGN { System::String^ get(); }
        static property System::String^ SUPERSCRIPT { System::String^ get(); }
        static property System::String^ UNIVERSAL_ACCESS { System::String^ get(); }
        static property System::String^ USER_MD { System::String^ get(); }
        static property System::String^ ALIGN_LEFT { System::String^ get(); }
        static property System::String^ TABLETS { System::String^ get(); }
        static property System::String^ MOTORCYCLE { System::String^ get(); }
        static property System::String^ KEYBOARD { System::String^ get(); }
        static property System::String^ BATTERY_HALF { System::String^ get(); }
        static property System::String^ ANGLE_UP { System::String^ get(); }
        static property System::String^ LIST_ALT { System::String^ get(); }
        static property System::String^ LEVEL_DOWN_ALT { System::String^ get(); }
        static property System::String^ PAPERCLIP { System::String^ get(); }
        static property System::String^ SORT_AMOUNT_UP { System::String^ get(); }
        static property System::String^ COFFEE { System::String^ get(); }
        static property System::String^ TABLET_ALT { System::String^ get(); }
        static property System::String^ SORT_ALPHA_UP { System::String^ get(); }
        static property System::String^ AUDIO_DESCRIPTION { System::String^ get(); }
        static property System::String^ PRESCRIPTION_BOTTLE { System::String^ get(); }
        static property System::String^ SYNC_ALT { System::String^ get(); }
        static property System::String^ HAND_POINT_RIGHT { System::String^ get(); }
        static property System::String^ SEARCH { System::String^ get(); }
        static property System::String^ EDIT { System::String^ get(); }
        static property System::String^ UNIVERSITY { System::String^ get(); }
        static property System::String^ VOLUME_OFF { System::String^ get(); }
        static property System::String^ INBOX { System::String^ get(); }
        static property System::String^ SQUARE { System::String^ get(); }
        static property System::String^ ELLIPSIS_V { System::String^ get(); }
        static property System::String^ BALANCE_SCALE { System::String^ get(); }
        static property System::String^ CLOSED_CAPTIONING { System::String^ get(); }
        static property System::String^ STRIKETHROUGH { System::String^ get(); }
        static property System::String^ QRCODE { System::String^ get(); }
        static property System::String^ UNLOCK { System::String^ get(); }
        static property System::String^ ELLIPSIS_H { System::String^ get(); }
        static property System::String^ PILLS { System::String^ get(); }
        static property System::String^ EXCLAMATION { System::String^ get(); }
        static property System::String^ RUPEE_SIGN { System::String^ get(); }
        static property System::String^ ASSISTIVE_LISTENING_SYSTEMS { System::String^ get(); }
        static property System::String^ POUND_SIGN { System::String^ get(); }
        static property System::String^ BATTERY_QUARTER { System::String^ get(); }
        static property System::String^ PRINT { System::String^ get(); }
        static property System::String^ SORT_NUMERIC_UP { System::String^ get(); }
        static property System::String^ VIDEO_SLASH { System::String^ get(); }
        static property System::String^ LOCATION_ARROW { System::String^ get(); }
        static property System::String^ UMBRELLA { System::String^ get(); }
        static property System::String^ UNDO { System::String^ get(); }
        static property System::String^ MARS { System::String^ get(); }
        static property System::String^ CHEVRON_DOWN { System::String^ get(); }
        static property System::String^ MARS_STROKE { System::String^ get(); }
        static property System::String^ INDENT { System::String^ get(); }
        static property System::String^ LANGUAGE { System::String^ get(); }
        static property System::String^ ARROW_ALT_CIRCLE_UP { System::String^ get(); }
        static property System::String^ HEADPHONES { System::String^ get(); }
        static property System::String^ TIMES { System::String^ get(); }
        static property System::String^ FILTER { System::String^ get(); }
        static property System::String^ PLANE { System::String^ get(); }
        static property System::String^ FOLDER_OPEN { System::String^ get(); }
        static property System::String^ HEARTBEAT { System::String^ get(); }
        static property System::String^ THUMBTACK { System::String^ get(); }
        static property System::String^ BLIND { System::String^ get(); }
        static property System::String^ CODE_BRANCH { System::String^ get(); }
        static property System::String^ PHONE_SQUARE { System::String^ get(); }
        static property System::String^ TEXT_HEIGHT { System::String^ get(); }
        static property System::String^ SHOPPING_BASKET { System::String^ get(); }
        static property System::String^ LONG_ARROW_ALT_LEFT { System::String^ get(); }
        static property System::String^ MERCURY { System::String^ get(); }
        static property System::String^ SORT_AMOUNT_DOWN { System::String^ get(); }
        static property System::String^ TEXT_WIDTH { System::String^ get(); }
        static property System::String^ RSS_SQUARE { System::String^ get(); }
        static property System::String^ PARACHUTE_BOX { System::String^ get(); }
        static property System::String^ WINDOW_MAXIMIZE { System::String^ get(); }
        static property System::String^ SORT_DOWN { System::String^ get(); }
        static property System::String^ CLOUD_UPLOAD_ALT { System::String^ get(); }
        static property System::String^ SORT_UP { System::String^ get(); }
        static property System::String^ SIGN_OUT_ALT { System::String^ get(); }
        static property System::String^ SIGN_IN_ALT { System::String^ get(); }
        static property System::String^ SHARE_ALT { System::String^ get(); }
        static property System::String^ CALENDAR_CHECK { System::String^ get(); }
        static property System::String^ VIAL { System::String^ get(); }
        static property System::String^ DATABASE { System::String^ get(); }
        static property System::String^ TREE { System::String^ get(); }
        static property System::String^ BED { System::String^ get(); }
        static property System::String^ SHOWER { System::String^ get(); }
        static property System::String^ MEDKIT { System::String^ get(); }
        static property System::String^ VIDEO { System::String^ get(); }
        static property System::String^ TOGGLE_OFF { System::String^ get(); }
        static property System::String^ MAP_MARKER_ALT { System::String^ get(); }
        static property System::String^ SHEKEL_SIGN { System::String^ get(); }
        static property System::String^ COMMENT_DOTS { System::String^ get(); }
        static property System::String^ BELL_SLASH { System::String^ get(); }
        static property System::String^ SHARE_ALT_SQUARE { System::String^ get(); }
        static property System::String^ CALENDAR { System::String^ get(); }
        static property System::String^ UNDO_ALT { System::String^ get(); }
        static property System::String^ FOOTBALL_BALL { System::String^ get(); }
        static property System::String^ ALLERGIES { System::String^ get(); }
        static property System::String^ ID_CARD { System::String^ get(); }
        static property System::String^ REDO_ALT { System::String^ get(); }
        static property System::String^ COUCH { System::String^ get(); }
        static property System::String^ PLAY_CIRCLE { System::String^ get(); }
        static property System::String^ CHESS { System::String^ get(); }
        static property System::String^ THERMOMETER { System::String^ get(); }
        static property System::String^ SNOWFLAKE { System::String^ get(); }
        static property System::String^ WRENCH { System::String^ get(); }
        static property System::String^ PLAY { System::String^ get(); }
        static property System::String^ DOLLAR_SIGN { System::String^ get(); }
        static property System::String^ AMBULANCE { System::String^ get(); }
        static property System::String^ COMPRESS { System::String^ get(); }
        static property System::String^ ANGLE_RIGHT { System::String^ get(); }
        static property System::String^ CHESS_QUEEN { System::String^ get(); }
        static property System::String^ CHART_AREA { System::String^ get(); }
        static property System::String^ EURO_SIGN { System::String^ get(); }
        static property System::String^ EJECT { System::String^ get(); }
        static property System::String^ MOBILE { System::String^ get(); }
        static property System::String^ HOURGLASS_END { System::String^ get(); }
        static property System::String^ BOX_OPEN { System::String^ get(); }
        static property System::String^ FUTBOL { System::String^ get(); }
        static property System::String^ BULLSEYE { System::String^ get(); }
        static property System::String^ FILE_EXCEL { System::String^ get(); }
        static property System::String^ LIGHTBULB { System::String^ get(); }
        static property System::String^ BOMB { System::String^ get(); }
        static property System::String^ RANDOM { System::String^ get(); }
        static property System::String^ CHESS_ROOK { System::String^ get(); }
        static property System::String^ TTY { System::String^ get(); }
        static property System::String^ BOOKMARK { System::String^ get(); }
        static property System::String^ ARROWS_ALT_V { System::String^ get(); }
        static property System::String^ EYE_DROPPER { System::String^ get(); }
        static property System::String^ FONT { System::String^ get(); }
        static property System::String^ CAMERA_RETRO { System::String^ get(); }
        static property System::String^ COPYRIGHT { System::String^ get(); }
        static property System::String^ RUBLE_SIGN { System::String^ get(); }
        static property System::String^ HOCKEY_PUCK { System::String^ get(); }
        static property System::String^ FILE_POWERPOINT { System::String^ get(); }
        static property System::String^ TAPE { System::String^ get(); }
        static property System::String^ SHOPPING_BAG { System::String^ get(); }
        static property System::String^ STOP_CIRCLE { System::String^ get(); }
        static property System::String^ FOLDER { System::String^ get(); }
        static property System::String^ RSS { System::String^ get(); }
        static property System::String^ LAPTOP { System::String^ get(); }
        static property System::String^ COLUMNS { System::String^ get(); }
        static property System::String^ POWER_OFF { System::String^ get(); }
        static property System::String^ CUBE { System::String^ get(); }
        static property System::String^ CAPSULES { System::String^ get(); }
        static property System::String^ CHEVRON_CIRCLE_UP { System::String^ get(); }
        static property System::String^ STOP { System::String^ get(); }
        static property System::String^ FILE_ARCHIVE { System::String^ get(); }
        static property System::String^ GLASS_MARTINI { System::String^ get(); }
        static property System::String^ MARS_STROKE_H { System::String^ get(); }
        static property System::String^ COMPASS { System::String^ get(); }
        static property System::String^ ADDRESS_BOOK { System::String^ get(); }
        static property System::String^ LIST_OL { System::String^ get(); }
        static property System::String^ PROCEDURES { System::String^ get(); }
        static property System::String^ GEM { System::String^ get(); }
        static property System::String^ WINE_GLASS { System::String^ get(); }
        static property System::String^ MICROCHIP { System::String^ get(); }
        static property System::String^ BAN { System::String^ get(); }
        static property System::String^ FIGHTER_JET { System::String^ get(); }
        static property System::String^ SPACE_SHUTTLE { System::String^ get(); }
        static property System::String^ BARS { System::String^ get(); }
        static property System::String^ ARROW_ALT_CIRCLE_DOWN { System::String^ get(); }
        static property System::String^ MAP_PIN { System::String^ get(); }
        static property System::String^ INFO_CIRCLE { System::String^ get(); }
        static property System::String^ MONEY_BILL_ALT { System::String^ get(); }
        static property System::String^ ALIGN_CENTER { System::String^ get(); }
        static property System::String^ SORT_ALPHA_DOWN { System::String^ get(); }
        static property System::String^ DONATE { System::String^ get(); }
        static property System::String^ MAP_SIGNS { System::String^ get(); }
        static property System::String^ RETWEET { System::String^ get(); }
        static property System::String^ HOURGLASS { System::String^ get(); }
        static property System::String^ YEN_SIGN { System::String^ get(); }
        static property System::String^ UNDERLINE { System::String^ get(); }
        static property System::String^ HAND_PAPER { System::String^ get(); }
        static property System::String^ SUBSCRIPT { System::String^ get(); }
        static property System::String^ TIMES_CIRCLE { System::String^ get(); }
        static property System::String^ KEY { System::String^ get(); }
        static property System::String^ TH_LIST { System::String^ get(); }
        static property System::String^ CUBES { System::String^ get(); }
        static property System::String^ TABLET { System::String^ get(); }
        static property System::String^ CREDIT_CARD { System::String^ get(); }
        static property System::String^ ARROW_CIRCLE_LEFT { System::String^ get(); }
        static property System::String^ MINUS { System::String^ get(); }
        static property System::String^ ARROWS_ALT_H { System::String^ get(); }
        static property System::String^ USER_SECRET { System::String^ get(); }
        static property System::String^ COG { System::String^ get(); }
        static property System::String^ ARROW_RIGHT { System::String^ get(); }
        static property System::String^ FILE_VIDEO { System::String^ get(); }
        static property System::String^ ARROW_ALT_CIRCLE_RIGHT { System::String^ get(); }
        static property System::String^ UTENSILS { System::String^ get(); }
        static property System::String^ BELL { System::String^ get(); }
        static property System::String^ POO { System::String^ get(); }
        static property System::String^ TABLE { System::String^ get(); }
        static property System::String^ PALLET { System::String^ get(); }
        static property System::String^ THUMBS_UP { System::String^ get(); }
        static property System::String^ TINT { System::String^ get(); }
        static property System::String^ HAND_PEACE { System::String^ get(); }
        static property System::String^ ALIGN_RIGHT { System::String^ get(); }
        static property System::String^ QUOTE_RIGHT { System::String^ get(); }
        static property System::String^ BEER { System::String^ get(); }
        static property System::String^ FIRST_AID { System::String^ get(); }
        static property System::String^ ERASER { System::String^ get(); }
        static property System::String^ SQUARE_FULL { System::String^ get(); }
        static property System::String^ DOLLY { System::String^ get(); }
        static property System::String^ HAND_HOLDING { System::String^ get(); }
        static property System::String^ HOURGLASS_START { System::String^ get(); }
        static property System::String^ FAST_BACKWARD { System::String^ get(); }
        static property System::String^ FIRE { System::String^ get(); }
        static property System::String^ FAST_FORWARD { System::String^ get(); }
        static property System::String^ VENUS_DOUBLE { System::String^ get(); }
        static property System::String^ VENUS { System::String^ get(); }
        static property System::String^ HASHTAG { System::String^ get(); }
        static property System::String^ SMOKING { System::String^ get(); }
        static property System::String^ PENCIL_ALT { System::String^ get(); }
        static property System::String^ TRUCK_LOADING { System::String^ get(); }
        static property System::String^ EXPAND_ARROWS_ALT { System::String^ get(); }
        static property System::String^ CARET_SQUARE_DOWN { System::String^ get(); }
        static property System::String^ HDD { System::String^ get(); }
        static property System::String^ OBJECT_GROUP { System::String^ get(); }
        static property System::String^ NEWSPAPER { System::String^ get(); }
        static property System::String^ HOSPITAL_ALT { System::String^ get(); }
        static property System::String^ ANCHOR { System::String^ get(); }
        static property System::String^ HAND_POINT_LEFT { System::String^ get(); }
        static property System::String^ USER_TIMES { System::String^ get(); }
        static property System::String^ CALCULATOR { System::String^ get(); }
        static property System::String^ ENVELOPE_SQUARE { System::String^ get(); }
        static property System::String^ FILE_MEDICAL { System::String^ get(); }
        static property System::String^ GENDERLESS { System::String^ get(); }
        static property System::String^ UNLOCK_ALT { System::String^ get(); }
        static property System::String^ PAW { System::String^ get(); }
        static property System::String^ HAND_HOLDING_HEART { System::String^ get(); }
        static property System::String^ ARCHIVE { System::String^ get(); }
        static property System::String^ PHONE_VOLUME { System::String^ get(); }
        static property System::String^ CARET_RIGHT { System::String^ get(); }
        static property System::String^ HAND_POINT_DOWN { System::String^ get(); }
        static property System::String^ MAP_MARKER { System::String^ get(); }
        static property System::String^ CALENDAR_ALT { System::String^ get(); }
        static property System::String^ MICROPHONE { System::String^ get(); }
        static property System::String^ AMERICAN_SIGN_LANGUAGE_INTERPRETING { System::String^ get(); }
        static property System::String^ BINOCULARS { System::String^ get(); }
        static property System::String^ STICKY_NOTE { System::String^ get(); }
        static property System::String^ USER { System::String^ get(); }
        static property System::String^ EXPAND { System::String^ get(); }
        static property System::String^ MINUS_CIRCLE { System::String^ get(); }
        static property System::String^ CHESS_PAWN { System::String^ get(); }
        static property System::String^ CALENDAR_MINUS { System::String^ get(); }
        static property System::String^ SLIDERS_H { System::String^ get(); }
        static property System::String^ CHESS_BOARD { System::String^ get(); }
        static property System::String^ BIRTHDAY_CAKE { System::String^ get(); }
        static property System::String^ GOLF_BALL { System::String^ get(); }
        static property System::String^ CHART_BAR { System::String^ get(); }
        static property System::String^ TAXI { System::String^ get(); }
        static property System::String^ COMMENT { System::String^ get(); }
        static property System::String^ ROCKET { System::String^ get(); }
        static property System::String^ HANDS { System::String^ get(); }
        static property System::String^ ARROWS_ALT { System::String^ get(); }
        static property System::String^ FILE_WORD { System::String^ get(); }
        static property System::String^ THERMOMETER_EMPTY { System::String^ get(); }
        static property System::String^ USER_CIRCLE { System::String^ get(); }
        static property System::String^ HANDSHAKE { System::String^ get(); }
        static property System::String^ CUT { System::String^ get(); }
        static property System::String^ STREET_VIEW { System::String^ get(); }
        static property System::String^ ARROW_CIRCLE_UP { System::String^ get(); }
        static property System::String^ BASKETBALL_BALL { System::String^ get(); }
        static property System::String^ DESKTOP { System::String^ get(); }
        static property System::String^ SPINNER { System::String^ get(); }
        static property System::String^ TOGGLE_ON { System::String^ get(); }
        static property System::String^ MINUS_SQUARE { System::String^ get(); }
        static property System::String^ STOPWATCH { System::String^ get(); }
        static property System::String^ ARROW_ALT_CIRCLE_LEFT { System::String^ get(); }
        static property System::String^ SAVE { System::String^ get(); }
        static property System::String^ TRASH_ALT { System::String^ get(); }
        static property System::String^ PUZZLE_PIECE { System::String^ get(); }
        static property System::String^ EXTERNAL_LINK_ALT { System::String^ get(); }
        static property System::String^ FROWN { System::String^ get(); }
        static property System::String^ SIGN_LANGUAGE { System::String^ get(); }
        static property System::String^ FILE_MEDICAL_ALT { System::String^ get(); }
        static property System::String^ ARROW_LEFT { System::String^ get(); }
        static property System::String^ BOXES { System::String^ get(); }
        static property System::String^ HAND_POINTER { System::String^ get(); }
        static property System::String^ PLUS_SQUARE { System::String^ get(); }
        static property System::String^ EXCLAMATION_TRIANGLE { System::String^ get(); }
        static property System::String^ GIFT { System::String^ get(); }
        static property System::String^ COGS { System::String^ get(); }
        static property System::String^ SIGNAL { System::String^ get(); }
        static property System::String^ ARROW_UP { System::String^ get(); }
        static property System::String^ SERVER { System::String^ get(); }
        static property System::String^ BATTERY_EMPTY { System::String^ get(); }
        static property System::String^ CHEVRON_CIRCLE_LEFT { System::String^ get(); }
        static property System::String^ SITEMAP { System::String^ get(); }
        static property System::String^ ID_BADGE { System::String^ get(); }
        static property System::String^ FILE_CODE { System::String^ get(); }
        static property System::String^ BOWLING_BALL { System::String^ get(); }
        static property System::String^ TERMINAL { System::String^ get(); }
        static property System::String^ BATTERY_FULL { System::String^ get(); }
        static property System::String^ DEAF { System::String^ get(); }
        static property System::String^ WINDOW_MINIMIZE { System::String^ get(); }
        static property System::String^ MARS_DOUBLE { System::String^ get(); }
        static property System::String^ EXCHANGE_ALT { System::String^ get(); }
        static property System::String^ HOME { System::String^ get(); }
        static property System::String^ COMMENT_ALT { System::String^ get(); }
        static property System::String^ SEARCH_MINUS { System::String^ get(); }
        static property System::String^ UTENSIL_SPOON { System::String^ get(); }
        static property System::String^ QUIDDITCH { System::String^ get(); }
        static property System::String^ EXCLAMATION_CIRCLE { System::String^ get(); }
        static property System::String^ COMMENTS { System::String^ get(); }
        static property System::String^ MOON { System::String^ get(); }
        static property System::String^ CARET_SQUARE_RIGHT { System::String^ get(); }
        static property System::String^ CHART_PIE { System::String^ get(); }
        static property System::String^ BOLD { System::String^ get(); }
        static property System::String^ BARCODE { System::String^ get(); }
        static property System::String^ HANDS_HELPING { System::String^ get(); }
        static property System::String^ BOLT { System::String^ get(); }
        static property System::String^ THERMOMETER_QUARTER { System::String^ get(); }
        static property System::String^ DNA { System::String^ get(); }
        static property System::String^ TROPHY { System::String^ get(); }
        static property System::String^ BRAILLE { System::String^ get(); }
        static property System::String^ INDUSTRY { System::String^ get(); }
        static property System::String^ CLOUD_DOWNLOAD_ALT { System::String^ get(); }
        static property System::String^ PLUS { System::String^ get(); }
        static property System::String^ LIST_UL { System::String^ get(); }
        static property System::String^ ROAD { System::String^ get(); }
        static property System::String^ VOLUME_DOWN { System::String^ get(); }
        static property System::String^ QUESTION_CIRCLE { System::String^ get(); }
        static property System::String^ TRADEMARK { System::String^ get(); }
        static property System::String^ IMAGE { System::String^ get(); }
        static property System::String^ CHILD { System::String^ get(); }
        static property System::String^ ANGLE_DOUBLE_RIGHT { System::String^ get(); }
        static property System::String^ BATH { System::String^ get(); }
        static property System::String^ REPLY_ALL { System::String^ get(); }
        static property System::String^ FEMALE { System::String^ get(); }
        static property System::String^ SYRINGE { System::String^ get(); }
        static property System::String^ CIRCLE_NOTCH { System::String^ get(); }
        static property System::String^ CARET_SQUARE_LEFT { System::String^ get(); }
        static property System::String^ WEIGHT { System::String^ get(); }
        static property System::String^ SHARE_SQUARE { System::String^ get(); }
        static property System::String^ TABLE_TENNIS { System::String^ get(); }
        static property System::String^ THERMOMETER_HALF { System::String^ get(); }
        static property System::String^ QUESTION { System::String^ get(); }
        static property System::String^ VIALS { System::String^ get(); }
        static property System::String^ LOW_VISION { System::String^ get(); }
        static property System::String^ SHIPPING_FAST { System::String^ get(); }
        static property System::String^ ITALIC { System::String^ get(); }
        static property System::String^ FORWARD { System::String^ get(); }
        static property System::String^ GLOBE { System::String^ get(); }
        static property System::String^ THUMBS_DOWN { System::String^ get(); }
        static property System::String^ CHEVRON_RIGHT { System::String^ get(); }
        static property System::String^ TACHOMETER_ALT { System::String^ get(); }
        static property System::String^ BUS { System::String^ get(); }
        static property System::String^ REGISTERED { System::String^ get(); }
        static property System::String^ ANGLE_DOWN { System::String^ get(); }
        static property System::String^ HAND_ROCK { System::String^ get(); }
        static property System::String^ WINDOW_CLOSE { System::String^ get(); }
        static property System::String^ LINK { System::String^ get(); }
        static property System::String^ PODCAST { System::String^ get(); }
        static property System::String^ TRUCK_MOVING { System::String^ get(); }
        static property System::String^ BUG { System::String^ get(); }
        static property System::String^ SHIELD_ALT { System::String^ get(); }
        static property System::String^ INFO { System::String^ get(); }
        static property System::String^ CHESS_KING { System::String^ get(); }
        static property System::String^ NEUTER { System::String^ get(); }
        static property System::String^ PAINT_BRUSH { System::String^ get(); }
        static property System::String^ COMMENT_SLASH { System::String^ get(); }
        static property System::String^ SUITCASE { System::String^ get(); }
        static property System::String^ HOSPITAL_SYMBOL { System::String^ get(); }
        static property System::String^ X_RAY { System::String^ get(); }
        static property System::String^ DOT_CIRCLE { System::String^ get(); }
        static property System::String^ VENUS_MARS { System::String^ get(); }
        static property System::String^ PAUSE_CIRCLE { System::String^ get(); }
        static property System::String^ SORT_NUMERIC_DOWN { System::String^ get(); }
        static property System::String^ TH_LARGE { System::String^ get(); }
        static property System::String^ AT { System::String^ get(); }
        static property System::String^ FILE { System::String^ get(); }
        static property System::String^ STAR_HALF { System::String^ get(); }
        static property System::String^ FLAG_CHECKERED { System::String^ get(); }
        static property System::String^ SHIP { System::String^ get(); }
        static property System::String^ CHECK { System::String^ get(); }
        static property System::String^ FILM { System::String^ get(); }
        static property System::String^ LEMON { System::String^ get(); }
        static property System::String^ PERCENT { System::String^ get(); }
        static property System::String^ BOOK { System::String^ get(); }
        static property System::String^ THERMOMETER_THREE_QUARTERS { System::String^ get(); }
        static property System::String^ WAREHOUSE { System::String^ get(); }
        static property System::String^ TRANSGENDER { System::String^ get(); }
        static property System::String^ TRASH { System::String^ get(); }
        static property System::String^ FILE_AUDIO { System::String^ get(); }
        static property System::String^ LIRA_SIGN { System::String^ get(); }
        static property System::String^ STAR { System::String^ get(); }
        static property System::String^ USERS { System::String^ get(); }
        static property System::String^ TRANSGENDER_ALT { System::String^ get(); }
        static property System::String^ ASTERISK { System::String^ get(); }
        static property System::String^ PLUS_CIRCLE { System::String^ get(); }
        static property System::String^ CART_ARROW_DOWN { System::String^ get(); }
        static property System::String^ HAND_SCISSORS { System::String^ get(); }
        static property System::String^ LEAF { System::String^ get(); }
        static property System::String^ BUILDING { System::String^ get(); }
        static property System::String^ PRESCRIPTION_BOTTLE_ALT { System::String^ get(); }
        static property System::String^ PEOPLE_CARRY { System::String^ get(); }
        static property System::String^ BAND_AID { System::String^ get(); }
        static property System::String^ WIFI { System::String^ get(); }
        static property System::String^ LONG_ARROW_ALT_DOWN { System::String^ get(); }
        static property System::String^ ANGLE_DOUBLE_DOWN { System::String^ get(); }
        static property System::String^ CHEVRON_UP { System::String^ get(); }
        static property System::String^ HAND_SPOCK { System::String^ get(); }
        static property System::String^ STETHOSCOPE { System::String^ get(); }
        static property System::String^ BACKWARD { System::String^ get(); }
        static property System::String^ HAND_POINT_UP { System::String^ get(); }

    };

}