#include "FontAwesome.h"

namespace ImGuiCLI
{
    System::String^ ICON_FA::NOTES_MEDICAL::get() { return gcnew System::String(u8"\uf481"); }
    System::String^ ICON_FA::CODE::get() { return gcnew System::String(u8"\uf121"); }
    System::String^ ICON_FA::COPY::get() { return gcnew System::String(u8"\uf0c5"); }
    System::String^ ICON_FA::CHEVRON_CIRCLE_RIGHT::get() { return gcnew System::String(u8"\uf138"); }
    System::String^ ICON_FA::CROSSHAIRS::get() { return gcnew System::String(u8"\uf05b"); }
    System::String^ ICON_FA::EXTERNAL_LINK_SQUARE_ALT::get() { return gcnew System::String(u8"\uf360"); }
    System::String^ ICON_FA::HAND_LIZARD::get() { return gcnew System::String(u8"\uf258"); }
    System::String^ ICON_FA::CHESS_BISHOP::get() { return gcnew System::String(u8"\uf43a"); }
    System::String^ ICON_FA::ANGLE_DOUBLE_LEFT::get() { return gcnew System::String(u8"\uf100"); }
    System::String^ ICON_FA::TH::get() { return gcnew System::String(u8"\uf00a"); }
    System::String^ ICON_FA::ANGLE_LEFT::get() { return gcnew System::String(u8"\uf104"); }
    System::String^ ICON_FA::RECYCLE::get() { return gcnew System::String(u8"\uf1b8"); }
    System::String^ ICON_FA::SMILE::get() { return gcnew System::String(u8"\uf118"); }
    System::String^ ICON_FA::PIGGY_BANK::get() { return gcnew System::String(u8"\uf4d3"); }
    System::String^ ICON_FA::OUTDENT::get() { return gcnew System::String(u8"\uf03b"); }
    System::String^ ICON_FA::FAX::get() { return gcnew System::String(u8"\uf1ac"); }
    System::String^ ICON_FA::CALENDAR_PLUS::get() { return gcnew System::String(u8"\uf271"); }
    System::String^ ICON_FA::LONG_ARROW_ALT_RIGHT::get() { return gcnew System::String(u8"\uf30b"); }
    System::String^ ICON_FA::IMAGES::get() { return gcnew System::String(u8"\uf302"); }
    System::String^ ICON_FA::GAVEL::get() { return gcnew System::String(u8"\uf0e3"); }
    System::String^ ICON_FA::FIRE_EXTINGUISHER::get() { return gcnew System::String(u8"\uf134"); }
    System::String^ ICON_FA::VOLUME_UP::get() { return gcnew System::String(u8"\uf028"); }
    System::String^ ICON_FA::CLIPBOARD_LIST::get() { return gcnew System::String(u8"\uf46d"); }
    System::String^ ICON_FA::CARET_UP::get() { return gcnew System::String(u8"\uf0d8"); }
    System::String^ ICON_FA::FILE_PDF::get() { return gcnew System::String(u8"\uf1c1"); }
    System::String^ ICON_FA::MAGIC::get() { return gcnew System::String(u8"\uf0d0"); }
    System::String^ ICON_FA::SEEDLING::get() { return gcnew System::String(u8"\uf4d8"); }
    System::String^ ICON_FA::LIST::get() { return gcnew System::String(u8"\uf03a"); }
    System::String^ ICON_FA::UPLOAD::get() { return gcnew System::String(u8"\uf093"); }
    System::String^ ICON_FA::MAGNET::get() { return gcnew System::String(u8"\uf076"); }
    System::String^ ICON_FA::ADJUST::get() { return gcnew System::String(u8"\uf042"); }
    System::String^ ICON_FA::SUBWAY::get() { return gcnew System::String(u8"\uf239"); }
    System::String^ ICON_FA::HEADING::get() { return gcnew System::String(u8"\uf1dc"); }
    System::String^ ICON_FA::CHECK_CIRCLE::get() { return gcnew System::String(u8"\uf058"); }
    System::String^ ICON_FA::ARROW_DOWN::get() { return gcnew System::String(u8"\uf063"); }
    System::String^ ICON_FA::BICYCLE::get() { return gcnew System::String(u8"\uf206"); }
    System::String^ ICON_FA::SYNC::get() { return gcnew System::String(u8"\uf021"); }
    System::String^ ICON_FA::CROP::get() { return gcnew System::String(u8"\uf125"); }
    System::String^ ICON_FA::SIGN::get() { return gcnew System::String(u8"\uf4d9"); }
    System::String^ ICON_FA::ARROW_CIRCLE_DOWN::get() { return gcnew System::String(u8"\uf0ab"); }
    System::String^ ICON_FA::PAPER_PLANE::get() { return gcnew System::String(u8"\uf1d8"); }
    System::String^ ICON_FA::DOWNLOAD::get() { return gcnew System::String(u8"\uf019"); }
    System::String^ ICON_FA::VOLLEYBALL_BALL::get() { return gcnew System::String(u8"\uf45f"); }
    System::String^ ICON_FA::RIBBON::get() { return gcnew System::String(u8"\uf4d6"); }
    System::String^ ICON_FA::CARET_DOWN::get() { return gcnew System::String(u8"\uf0d7"); }
    System::String^ ICON_FA::CHEVRON_LEFT::get() { return gcnew System::String(u8"\uf053"); }
    System::String^ ICON_FA::CARET_LEFT::get() { return gcnew System::String(u8"\uf0d9"); }
    System::String^ ICON_FA::CLOCK::get() { return gcnew System::String(u8"\uf017"); }
    System::String^ ICON_FA::SUN::get() { return gcnew System::String(u8"\uf185"); }
    System::String^ ICON_FA::CART_PLUS::get() { return gcnew System::String(u8"\uf217"); }
    System::String^ ICON_FA::CLIPBOARD::get() { return gcnew System::String(u8"\uf328"); }
    System::String^ ICON_FA::PHONE_SLASH::get() { return gcnew System::String(u8"\uf3dd"); }
    System::String^ ICON_FA::REPLY::get() { return gcnew System::String(u8"\uf3e5"); }
    System::String^ ICON_FA::HOURGLASS_HALF::get() { return gcnew System::String(u8"\uf252"); }
    System::String^ ICON_FA::LONG_ARROW_ALT_UP::get() { return gcnew System::String(u8"\uf30c"); }
    System::String^ ICON_FA::GRADUATION_CAP::get() { return gcnew System::String(u8"\uf19d"); }
    System::String^ ICON_FA::CHESS_KNIGHT::get() { return gcnew System::String(u8"\uf441"); }
    System::String^ ICON_FA::BURN::get() { return gcnew System::String(u8"\uf46a"); }
    System::String^ ICON_FA::TAGS::get() { return gcnew System::String(u8"\uf02c"); }
    System::String^ ICON_FA::FILE_ALT::get() { return gcnew System::String(u8"\uf15c"); }
    System::String^ ICON_FA::MEH::get() { return gcnew System::String(u8"\uf11a"); }
    System::String^ ICON_FA::PAUSE::get() { return gcnew System::String(u8"\uf04c"); }
    System::String^ ICON_FA::BOX::get() { return gcnew System::String(u8"\uf466"); }
    System::String^ ICON_FA::DIAGNOSES::get() { return gcnew System::String(u8"\uf470"); }
    System::String^ ICON_FA::FILE_IMAGE::get() { return gcnew System::String(u8"\uf1c5"); }
    System::String^ ICON_FA::TV::get() { return gcnew System::String(u8"\uf26c"); }
    System::String^ ICON_FA::ARROW_CIRCLE_RIGHT::get() { return gcnew System::String(u8"\uf0a9"); }
    System::String^ ICON_FA::CALENDAR_TIMES::get() { return gcnew System::String(u8"\uf273"); }
    System::String^ ICON_FA::TASKS::get() { return gcnew System::String(u8"\uf0ae"); }
    System::String^ ICON_FA::GAMEPAD::get() { return gcnew System::String(u8"\uf11b"); }
    System::String^ ICON_FA::QUOTE_LEFT::get() { return gcnew System::String(u8"\uf10d"); }
    System::String^ ICON_FA::MOBILE_ALT::get() { return gcnew System::String(u8"\uf3cd"); }
    System::String^ ICON_FA::EYE_SLASH::get() { return gcnew System::String(u8"\uf070"); }
    System::String^ ICON_FA::REDO::get() { return gcnew System::String(u8"\uf01e"); }
    System::String^ ICON_FA::CLOUD::get() { return gcnew System::String(u8"\uf0c2"); }
    System::String^ ICON_FA::HAND_HOLDING_USD::get() { return gcnew System::String(u8"\uf4c0"); }
    System::String^ ICON_FA::EYE::get() { return gcnew System::String(u8"\uf06e"); }
    System::String^ ICON_FA::CERTIFICATE::get() { return gcnew System::String(u8"\uf0a3"); }
    System::String^ ICON_FA::BASEBALL_BALL::get() { return gcnew System::String(u8"\uf433"); }
    System::String^ ICON_FA::PASTE::get() { return gcnew System::String(u8"\uf0ea"); }
    System::String^ ICON_FA::HOSPITAL::get() { return gcnew System::String(u8"\uf0f8"); }
    System::String^ ICON_FA::CAMERA::get() { return gcnew System::String(u8"\uf030"); }
    System::String^ ICON_FA::MUSIC::get() { return gcnew System::String(u8"\uf001"); }
    System::String^ ICON_FA::PEN_SQUARE::get() { return gcnew System::String(u8"\uf14b"); }
    System::String^ ICON_FA::BRIEFCASE_MEDICAL::get() { return gcnew System::String(u8"\uf469"); }
    System::String^ ICON_FA::SORT::get() { return gcnew System::String(u8"\uf0dc"); }
    System::String^ ICON_FA::PLUG::get() { return gcnew System::String(u8"\uf1e6"); }
    System::String^ ICON_FA::SHOPPING_CART::get() { return gcnew System::String(u8"\uf07a"); }
    System::String^ ICON_FA::MOUSE_POINTER::get() { return gcnew System::String(u8"\uf245"); }
    System::String^ ICON_FA::ENVELOPE::get() { return gcnew System::String(u8"\uf0e0"); }
    System::String^ ICON_FA::WINDOW_RESTORE::get() { return gcnew System::String(u8"\uf2d2"); }
    System::String^ ICON_FA::PHONE::get() { return gcnew System::String(u8"\uf095"); }
    System::String^ ICON_FA::FLAG::get() { return gcnew System::String(u8"\uf024"); }
    System::String^ ICON_FA::TRAIN::get() { return gcnew System::String(u8"\uf238"); }
    System::String^ ICON_FA::BULLHORN::get() { return gcnew System::String(u8"\uf0a1"); }
    System::String^ ICON_FA::CLIPBOARD_CHECK::get() { return gcnew System::String(u8"\uf46c"); }
    System::String^ ICON_FA::CIRCLE::get() { return gcnew System::String(u8"\uf111"); }
    System::String^ ICON_FA::DOLLY_FLATBED::get() { return gcnew System::String(u8"\uf474"); }
    System::String^ ICON_FA::ADDRESS_CARD::get() { return gcnew System::String(u8"\uf2bb"); }
    System::String^ ICON_FA::I_CURSOR::get() { return gcnew System::String(u8"\uf246"); }
    System::String^ ICON_FA::CAR::get() { return gcnew System::String(u8"\uf1b9"); }
    System::String^ ICON_FA::CARET_SQUARE_UP::get() { return gcnew System::String(u8"\uf151"); }
    System::String^ ICON_FA::PARAGRAPH::get() { return gcnew System::String(u8"\uf1dd"); }
    System::String^ ICON_FA::MALE::get() { return gcnew System::String(u8"\uf183"); }
    System::String^ ICON_FA::HISTORY::get() { return gcnew System::String(u8"\uf1da"); }
    System::String^ ICON_FA::H_SQUARE::get() { return gcnew System::String(u8"\uf0fd"); }
    System::String^ ICON_FA::HEART::get() { return gcnew System::String(u8"\uf004"); }
    System::String^ ICON_FA::LOCK_OPEN::get() { return gcnew System::String(u8"\uf3c1"); }
    System::String^ ICON_FA::SEARCH_PLUS::get() { return gcnew System::String(u8"\uf00e"); }
    System::String^ ICON_FA::LIFE_RING::get() { return gcnew System::String(u8"\uf1cd"); }
    System::String^ ICON_FA::LOCK::get() { return gcnew System::String(u8"\uf023"); }
    System::String^ ICON_FA::STEP_FORWARD::get() { return gcnew System::String(u8"\uf051"); }
    System::String^ ICON_FA::SHARE::get() { return gcnew System::String(u8"\uf064"); }
    System::String^ ICON_FA::TAG::get() { return gcnew System::String(u8"\uf02b"); }
    System::String^ ICON_FA::ALIGN_JUSTIFY::get() { return gcnew System::String(u8"\uf039"); }
    System::String^ ICON_FA::CHEVRON_CIRCLE_DOWN::get() { return gcnew System::String(u8"\uf13a"); }
    System::String^ ICON_FA::TICKET_ALT::get() { return gcnew System::String(u8"\uf3ff"); }
    System::String^ ICON_FA::BATTERY_THREE_QUARTERS::get() { return gcnew System::String(u8"\uf241"); }
    System::String^ ICON_FA::MAP::get() { return gcnew System::String(u8"\uf279"); }
    System::String^ ICON_FA::OBJECT_UNGROUP::get() { return gcnew System::String(u8"\uf248"); }
    System::String^ ICON_FA::BRIEFCASE::get() { return gcnew System::String(u8"\uf0b1"); }
    System::String^ ICON_FA::MARS_STROKE_V::get() { return gcnew System::String(u8"\uf22a"); }
    System::String^ ICON_FA::CLONE::get() { return gcnew System::String(u8"\uf24d"); }
    System::String^ ICON_FA::THERMOMETER_FULL::get() { return gcnew System::String(u8"\uf2c7"); }
    System::String^ ICON_FA::ID_CARD_ALT::get() { return gcnew System::String(u8"\uf47f"); }
    System::String^ ICON_FA::CHECK_SQUARE::get() { return gcnew System::String(u8"\uf14a"); }
    System::String^ ICON_FA::CHART_LINE::get() { return gcnew System::String(u8"\uf201"); }
    System::String^ ICON_FA::UNLINK::get() { return gcnew System::String(u8"\uf127"); }
    System::String^ ICON_FA::DOVE::get() { return gcnew System::String(u8"\uf4ba"); }
    System::String^ ICON_FA::ENVELOPE_OPEN::get() { return gcnew System::String(u8"\uf2b6"); }
    System::String^ ICON_FA::STEP_BACKWARD::get() { return gcnew System::String(u8"\uf048"); }
    System::String^ ICON_FA::WHEELCHAIR::get() { return gcnew System::String(u8"\uf193"); }
    System::String^ ICON_FA::MICROPHONE_SLASH::get() { return gcnew System::String(u8"\uf131"); }
    System::String^ ICON_FA::ANGLE_DOUBLE_UP::get() { return gcnew System::String(u8"\uf102"); }
    System::String^ ICON_FA::USER_PLUS::get() { return gcnew System::String(u8"\uf234"); }
    System::String^ ICON_FA::TRUCK::get() { return gcnew System::String(u8"\uf0d1"); }
    System::String^ ICON_FA::LEVEL_UP_ALT::get() { return gcnew System::String(u8"\uf3bf"); }
    System::String^ ICON_FA::FLASK::get() { return gcnew System::String(u8"\uf0c3"); }
    System::String^ ICON_FA::WON_SIGN::get() { return gcnew System::String(u8"\uf159"); }
    System::String^ ICON_FA::SUPERSCRIPT::get() { return gcnew System::String(u8"\uf12b"); }
    System::String^ ICON_FA::UNIVERSAL_ACCESS::get() { return gcnew System::String(u8"\uf29a"); }
    System::String^ ICON_FA::USER_MD::get() { return gcnew System::String(u8"\uf0f0"); }
    System::String^ ICON_FA::ALIGN_LEFT::get() { return gcnew System::String(u8"\uf036"); }
    System::String^ ICON_FA::TABLETS::get() { return gcnew System::String(u8"\uf490"); }
    System::String^ ICON_FA::MOTORCYCLE::get() { return gcnew System::String(u8"\uf21c"); }
    System::String^ ICON_FA::KEYBOARD::get() { return gcnew System::String(u8"\uf11c"); }
    System::String^ ICON_FA::BATTERY_HALF::get() { return gcnew System::String(u8"\uf242"); }
    System::String^ ICON_FA::ANGLE_UP::get() { return gcnew System::String(u8"\uf106"); }
    System::String^ ICON_FA::LIST_ALT::get() { return gcnew System::String(u8"\uf022"); }
    System::String^ ICON_FA::LEVEL_DOWN_ALT::get() { return gcnew System::String(u8"\uf3be"); }
    System::String^ ICON_FA::PAPERCLIP::get() { return gcnew System::String(u8"\uf0c6"); }
    System::String^ ICON_FA::SORT_AMOUNT_UP::get() { return gcnew System::String(u8"\uf161"); }
    System::String^ ICON_FA::COFFEE::get() { return gcnew System::String(u8"\uf0f4"); }
    System::String^ ICON_FA::TABLET_ALT::get() { return gcnew System::String(u8"\uf3fa"); }
    System::String^ ICON_FA::SORT_ALPHA_UP::get() { return gcnew System::String(u8"\uf15e"); }
    System::String^ ICON_FA::AUDIO_DESCRIPTION::get() { return gcnew System::String(u8"\uf29e"); }
    System::String^ ICON_FA::PRESCRIPTION_BOTTLE::get() { return gcnew System::String(u8"\uf485"); }
    System::String^ ICON_FA::SYNC_ALT::get() { return gcnew System::String(u8"\uf2f1"); }
    System::String^ ICON_FA::HAND_POINT_RIGHT::get() { return gcnew System::String(u8"\uf0a4"); }
    System::String^ ICON_FA::SEARCH::get() { return gcnew System::String(u8"\uf002"); }
    System::String^ ICON_FA::EDIT::get() { return gcnew System::String(u8"\uf044"); }
    System::String^ ICON_FA::UNIVERSITY::get() { return gcnew System::String(u8"\uf19c"); }
    System::String^ ICON_FA::VOLUME_OFF::get() { return gcnew System::String(u8"\uf026"); }
    System::String^ ICON_FA::INBOX::get() { return gcnew System::String(u8"\uf01c"); }
    System::String^ ICON_FA::SQUARE::get() { return gcnew System::String(u8"\uf0c8"); }
    System::String^ ICON_FA::ELLIPSIS_V::get() { return gcnew System::String(u8"\uf142"); }
    System::String^ ICON_FA::BALANCE_SCALE::get() { return gcnew System::String(u8"\uf24e"); }
    System::String^ ICON_FA::CLOSED_CAPTIONING::get() { return gcnew System::String(u8"\uf20a"); }
    System::String^ ICON_FA::STRIKETHROUGH::get() { return gcnew System::String(u8"\uf0cc"); }
    System::String^ ICON_FA::QRCODE::get() { return gcnew System::String(u8"\uf029"); }
    System::String^ ICON_FA::UNLOCK::get() { return gcnew System::String(u8"\uf09c"); }
    System::String^ ICON_FA::ELLIPSIS_H::get() { return gcnew System::String(u8"\uf141"); }
    System::String^ ICON_FA::PILLS::get() { return gcnew System::String(u8"\uf484"); }
    System::String^ ICON_FA::EXCLAMATION::get() { return gcnew System::String(u8"\uf12a"); }
    System::String^ ICON_FA::RUPEE_SIGN::get() { return gcnew System::String(u8"\uf156"); }
    System::String^ ICON_FA::ASSISTIVE_LISTENING_SYSTEMS::get() { return gcnew System::String(u8"\uf2a2"); }
    System::String^ ICON_FA::POUND_SIGN::get() { return gcnew System::String(u8"\uf154"); }
    System::String^ ICON_FA::BATTERY_QUARTER::get() { return gcnew System::String(u8"\uf243"); }
    System::String^ ICON_FA::PRINT::get() { return gcnew System::String(u8"\uf02f"); }
    System::String^ ICON_FA::SORT_NUMERIC_UP::get() { return gcnew System::String(u8"\uf163"); }
    System::String^ ICON_FA::VIDEO_SLASH::get() { return gcnew System::String(u8"\uf4e2"); }
    System::String^ ICON_FA::LOCATION_ARROW::get() { return gcnew System::String(u8"\uf124"); }
    System::String^ ICON_FA::UMBRELLA::get() { return gcnew System::String(u8"\uf0e9"); }
    System::String^ ICON_FA::UNDO::get() { return gcnew System::String(u8"\uf0e2"); }
    System::String^ ICON_FA::MARS::get() { return gcnew System::String(u8"\uf222"); }
    System::String^ ICON_FA::CHEVRON_DOWN::get() { return gcnew System::String(u8"\uf078"); }
    System::String^ ICON_FA::MARS_STROKE::get() { return gcnew System::String(u8"\uf229"); }
    System::String^ ICON_FA::INDENT::get() { return gcnew System::String(u8"\uf03c"); }
    System::String^ ICON_FA::LANGUAGE::get() { return gcnew System::String(u8"\uf1ab"); }
    System::String^ ICON_FA::ARROW_ALT_CIRCLE_UP::get() { return gcnew System::String(u8"\uf35b"); }
    System::String^ ICON_FA::HEADPHONES::get() { return gcnew System::String(u8"\uf025"); }
    System::String^ ICON_FA::TIMES::get() { return gcnew System::String(u8"\uf00d"); }
    System::String^ ICON_FA::FILTER::get() { return gcnew System::String(u8"\uf0b0"); }
    System::String^ ICON_FA::PLANE::get() { return gcnew System::String(u8"\uf072"); }
    System::String^ ICON_FA::FOLDER_OPEN::get() { return gcnew System::String(u8"\uf07c"); }
    System::String^ ICON_FA::HEARTBEAT::get() { return gcnew System::String(u8"\uf21e"); }
    System::String^ ICON_FA::THUMBTACK::get() { return gcnew System::String(u8"\uf08d"); }
    System::String^ ICON_FA::BLIND::get() { return gcnew System::String(u8"\uf29d"); }
    System::String^ ICON_FA::CODE_BRANCH::get() { return gcnew System::String(u8"\uf126"); }
    System::String^ ICON_FA::PHONE_SQUARE::get() { return gcnew System::String(u8"\uf098"); }
    System::String^ ICON_FA::TEXT_HEIGHT::get() { return gcnew System::String(u8"\uf034"); }
    System::String^ ICON_FA::SHOPPING_BASKET::get() { return gcnew System::String(u8"\uf291"); }
    System::String^ ICON_FA::LONG_ARROW_ALT_LEFT::get() { return gcnew System::String(u8"\uf30a"); }
    System::String^ ICON_FA::MERCURY::get() { return gcnew System::String(u8"\uf223"); }
    System::String^ ICON_FA::SORT_AMOUNT_DOWN::get() { return gcnew System::String(u8"\uf160"); }
    System::String^ ICON_FA::TEXT_WIDTH::get() { return gcnew System::String(u8"\uf035"); }
    System::String^ ICON_FA::RSS_SQUARE::get() { return gcnew System::String(u8"\uf143"); }
    System::String^ ICON_FA::PARACHUTE_BOX::get() { return gcnew System::String(u8"\uf4cd"); }
    System::String^ ICON_FA::WINDOW_MAXIMIZE::get() { return gcnew System::String(u8"\uf2d0"); }
    System::String^ ICON_FA::SORT_DOWN::get() { return gcnew System::String(u8"\uf0dd"); }
    System::String^ ICON_FA::CLOUD_UPLOAD_ALT::get() { return gcnew System::String(u8"\uf382"); }
    System::String^ ICON_FA::SORT_UP::get() { return gcnew System::String(u8"\uf0de"); }
    System::String^ ICON_FA::SIGN_OUT_ALT::get() { return gcnew System::String(u8"\uf2f5"); }
    System::String^ ICON_FA::SIGN_IN_ALT::get() { return gcnew System::String(u8"\uf2f6"); }
    System::String^ ICON_FA::SHARE_ALT::get() { return gcnew System::String(u8"\uf1e0"); }
    System::String^ ICON_FA::CALENDAR_CHECK::get() { return gcnew System::String(u8"\uf274"); }
    System::String^ ICON_FA::VIAL::get() { return gcnew System::String(u8"\uf492"); }
    System::String^ ICON_FA::DATABASE::get() { return gcnew System::String(u8"\uf1c0"); }
    System::String^ ICON_FA::TREE::get() { return gcnew System::String(u8"\uf1bb"); }
    System::String^ ICON_FA::BED::get() { return gcnew System::String(u8"\uf236"); }
    System::String^ ICON_FA::SHOWER::get() { return gcnew System::String(u8"\uf2cc"); }
    System::String^ ICON_FA::MEDKIT::get() { return gcnew System::String(u8"\uf0fa"); }
    System::String^ ICON_FA::VIDEO::get() { return gcnew System::String(u8"\uf03d"); }
    System::String^ ICON_FA::TOGGLE_OFF::get() { return gcnew System::String(u8"\uf204"); }
    System::String^ ICON_FA::MAP_MARKER_ALT::get() { return gcnew System::String(u8"\uf3c5"); }
    System::String^ ICON_FA::SHEKEL_SIGN::get() { return gcnew System::String(u8"\uf20b"); }
    System::String^ ICON_FA::COMMENT_DOTS::get() { return gcnew System::String(u8"\uf4ad"); }
    System::String^ ICON_FA::BELL_SLASH::get() { return gcnew System::String(u8"\uf1f6"); }
    System::String^ ICON_FA::SHARE_ALT_SQUARE::get() { return gcnew System::String(u8"\uf1e1"); }
    System::String^ ICON_FA::CALENDAR::get() { return gcnew System::String(u8"\uf133"); }
    System::String^ ICON_FA::UNDO_ALT::get() { return gcnew System::String(u8"\uf2ea"); }
    System::String^ ICON_FA::FOOTBALL_BALL::get() { return gcnew System::String(u8"\uf44e"); }
    System::String^ ICON_FA::ALLERGIES::get() { return gcnew System::String(u8"\uf461"); }
    System::String^ ICON_FA::ID_CARD::get() { return gcnew System::String(u8"\uf2c2"); }
    System::String^ ICON_FA::REDO_ALT::get() { return gcnew System::String(u8"\uf2f9"); }
    System::String^ ICON_FA::COUCH::get() { return gcnew System::String(u8"\uf4b8"); }
    System::String^ ICON_FA::PLAY_CIRCLE::get() { return gcnew System::String(u8"\uf144"); }
    System::String^ ICON_FA::CHESS::get() { return gcnew System::String(u8"\uf439"); }
    System::String^ ICON_FA::THERMOMETER::get() { return gcnew System::String(u8"\uf491"); }
    System::String^ ICON_FA::SNOWFLAKE::get() { return gcnew System::String(u8"\uf2dc"); }
    System::String^ ICON_FA::WRENCH::get() { return gcnew System::String(u8"\uf0ad"); }
    System::String^ ICON_FA::PLAY::get() { return gcnew System::String(u8"\uf04b"); }
    System::String^ ICON_FA::DOLLAR_SIGN::get() { return gcnew System::String(u8"\uf155"); }
    System::String^ ICON_FA::AMBULANCE::get() { return gcnew System::String(u8"\uf0f9"); }
    System::String^ ICON_FA::COMPRESS::get() { return gcnew System::String(u8"\uf066"); }
    System::String^ ICON_FA::ANGLE_RIGHT::get() { return gcnew System::String(u8"\uf105"); }
    System::String^ ICON_FA::CHESS_QUEEN::get() { return gcnew System::String(u8"\uf445"); }
    System::String^ ICON_FA::CHART_AREA::get() { return gcnew System::String(u8"\uf1fe"); }
    System::String^ ICON_FA::EURO_SIGN::get() { return gcnew System::String(u8"\uf153"); }
    System::String^ ICON_FA::EJECT::get() { return gcnew System::String(u8"\uf052"); }
    System::String^ ICON_FA::MOBILE::get() { return gcnew System::String(u8"\uf10b"); }
    System::String^ ICON_FA::HOURGLASS_END::get() { return gcnew System::String(u8"\uf253"); }
    System::String^ ICON_FA::BOX_OPEN::get() { return gcnew System::String(u8"\uf49e"); }
    System::String^ ICON_FA::FUTBOL::get() { return gcnew System::String(u8"\uf1e3"); }
    System::String^ ICON_FA::BULLSEYE::get() { return gcnew System::String(u8"\uf140"); }
    System::String^ ICON_FA::FILE_EXCEL::get() { return gcnew System::String(u8"\uf1c3"); }
    System::String^ ICON_FA::LIGHTBULB::get() { return gcnew System::String(u8"\uf0eb"); }
    System::String^ ICON_FA::BOMB::get() { return gcnew System::String(u8"\uf1e2"); }
    System::String^ ICON_FA::RANDOM::get() { return gcnew System::String(u8"\uf074"); }
    System::String^ ICON_FA::CHESS_ROOK::get() { return gcnew System::String(u8"\uf447"); }
    System::String^ ICON_FA::TTY::get() { return gcnew System::String(u8"\uf1e4"); }
    System::String^ ICON_FA::BOOKMARK::get() { return gcnew System::String(u8"\uf02e"); }
    System::String^ ICON_FA::ARROWS_ALT_V::get() { return gcnew System::String(u8"\uf338"); }
    System::String^ ICON_FA::EYE_DROPPER::get() { return gcnew System::String(u8"\uf1fb"); }
    System::String^ ICON_FA::FONT::get() { return gcnew System::String(u8"\uf031"); }
    System::String^ ICON_FA::CAMERA_RETRO::get() { return gcnew System::String(u8"\uf083"); }
    System::String^ ICON_FA::COPYRIGHT::get() { return gcnew System::String(u8"\uf1f9"); }
    System::String^ ICON_FA::RUBLE_SIGN::get() { return gcnew System::String(u8"\uf158"); }
    System::String^ ICON_FA::HOCKEY_PUCK::get() { return gcnew System::String(u8"\uf453"); }
    System::String^ ICON_FA::FILE_POWERPOINT::get() { return gcnew System::String(u8"\uf1c4"); }
    System::String^ ICON_FA::TAPE::get() { return gcnew System::String(u8"\uf4db"); }
    System::String^ ICON_FA::SHOPPING_BAG::get() { return gcnew System::String(u8"\uf290"); }
    System::String^ ICON_FA::STOP_CIRCLE::get() { return gcnew System::String(u8"\uf28d"); }
    System::String^ ICON_FA::FOLDER::get() { return gcnew System::String(u8"\uf07b"); }
    System::String^ ICON_FA::RSS::get() { return gcnew System::String(u8"\uf09e"); }
    System::String^ ICON_FA::LAPTOP::get() { return gcnew System::String(u8"\uf109"); }
    System::String^ ICON_FA::COLUMNS::get() { return gcnew System::String(u8"\uf0db"); }
    System::String^ ICON_FA::POWER_OFF::get() { return gcnew System::String(u8"\uf011"); }
    System::String^ ICON_FA::CUBE::get() { return gcnew System::String(u8"\uf1b2"); }
    System::String^ ICON_FA::CAPSULES::get() { return gcnew System::String(u8"\uf46b"); }
    System::String^ ICON_FA::CHEVRON_CIRCLE_UP::get() { return gcnew System::String(u8"\uf139"); }
    System::String^ ICON_FA::STOP::get() { return gcnew System::String(u8"\uf04d"); }
    System::String^ ICON_FA::FILE_ARCHIVE::get() { return gcnew System::String(u8"\uf1c6"); }
    System::String^ ICON_FA::GLASS_MARTINI::get() { return gcnew System::String(u8"\uf000"); }
    System::String^ ICON_FA::MARS_STROKE_H::get() { return gcnew System::String(u8"\uf22b"); }
    System::String^ ICON_FA::COMPASS::get() { return gcnew System::String(u8"\uf14e"); }
    System::String^ ICON_FA::ADDRESS_BOOK::get() { return gcnew System::String(u8"\uf2b9"); }
    System::String^ ICON_FA::LIST_OL::get() { return gcnew System::String(u8"\uf0cb"); }
    System::String^ ICON_FA::PROCEDURES::get() { return gcnew System::String(u8"\uf487"); }
    System::String^ ICON_FA::GEM::get() { return gcnew System::String(u8"\uf3a5"); }
    System::String^ ICON_FA::WINE_GLASS::get() { return gcnew System::String(u8"\uf4e3"); }
    System::String^ ICON_FA::MICROCHIP::get() { return gcnew System::String(u8"\uf2db"); }
    System::String^ ICON_FA::BAN::get() { return gcnew System::String(u8"\uf05e"); }
    System::String^ ICON_FA::FIGHTER_JET::get() { return gcnew System::String(u8"\uf0fb"); }
    System::String^ ICON_FA::SPACE_SHUTTLE::get() { return gcnew System::String(u8"\uf197"); }
    System::String^ ICON_FA::BARS::get() { return gcnew System::String(u8"\uf0c9"); }
    System::String^ ICON_FA::ARROW_ALT_CIRCLE_DOWN::get() { return gcnew System::String(u8"\uf358"); }
    System::String^ ICON_FA::MAP_PIN::get() { return gcnew System::String(u8"\uf276"); }
    System::String^ ICON_FA::INFO_CIRCLE::get() { return gcnew System::String(u8"\uf05a"); }
    System::String^ ICON_FA::MONEY_BILL_ALT::get() { return gcnew System::String(u8"\uf3d1"); }
    System::String^ ICON_FA::ALIGN_CENTER::get() { return gcnew System::String(u8"\uf037"); }
    System::String^ ICON_FA::SORT_ALPHA_DOWN::get() { return gcnew System::String(u8"\uf15d"); }
    System::String^ ICON_FA::DONATE::get() { return gcnew System::String(u8"\uf4b9"); }
    System::String^ ICON_FA::MAP_SIGNS::get() { return gcnew System::String(u8"\uf277"); }
    System::String^ ICON_FA::RETWEET::get() { return gcnew System::String(u8"\uf079"); }
    System::String^ ICON_FA::HOURGLASS::get() { return gcnew System::String(u8"\uf254"); }
    System::String^ ICON_FA::YEN_SIGN::get() { return gcnew System::String(u8"\uf157"); }
    System::String^ ICON_FA::UNDERLINE::get() { return gcnew System::String(u8"\uf0cd"); }
    System::String^ ICON_FA::HAND_PAPER::get() { return gcnew System::String(u8"\uf256"); }
    System::String^ ICON_FA::SUBSCRIPT::get() { return gcnew System::String(u8"\uf12c"); }
    System::String^ ICON_FA::TIMES_CIRCLE::get() { return gcnew System::String(u8"\uf057"); }
    System::String^ ICON_FA::KEY::get() { return gcnew System::String(u8"\uf084"); }
    System::String^ ICON_FA::TH_LIST::get() { return gcnew System::String(u8"\uf00b"); }
    System::String^ ICON_FA::CUBES::get() { return gcnew System::String(u8"\uf1b3"); }
    System::String^ ICON_FA::TABLET::get() { return gcnew System::String(u8"\uf10a"); }
    System::String^ ICON_FA::CREDIT_CARD::get() { return gcnew System::String(u8"\uf09d"); }
    System::String^ ICON_FA::ARROW_CIRCLE_LEFT::get() { return gcnew System::String(u8"\uf0a8"); }
    System::String^ ICON_FA::MINUS::get() { return gcnew System::String(u8"\uf068"); }
    System::String^ ICON_FA::ARROWS_ALT_H::get() { return gcnew System::String(u8"\uf337"); }
    System::String^ ICON_FA::USER_SECRET::get() { return gcnew System::String(u8"\uf21b"); }
    System::String^ ICON_FA::COG::get() { return gcnew System::String(u8"\uf013"); }
    System::String^ ICON_FA::ARROW_RIGHT::get() { return gcnew System::String(u8"\uf061"); }
    System::String^ ICON_FA::FILE_VIDEO::get() { return gcnew System::String(u8"\uf1c8"); }
    System::String^ ICON_FA::ARROW_ALT_CIRCLE_RIGHT::get() { return gcnew System::String(u8"\uf35a"); }
    System::String^ ICON_FA::UTENSILS::get() { return gcnew System::String(u8"\uf2e7"); }
    System::String^ ICON_FA::BELL::get() { return gcnew System::String(u8"\uf0f3"); }
    System::String^ ICON_FA::POO::get() { return gcnew System::String(u8"\uf2fe"); }
    System::String^ ICON_FA::TABLE::get() { return gcnew System::String(u8"\uf0ce"); }
    System::String^ ICON_FA::PALLET::get() { return gcnew System::String(u8"\uf482"); }
    System::String^ ICON_FA::THUMBS_UP::get() { return gcnew System::String(u8"\uf164"); }
    System::String^ ICON_FA::TINT::get() { return gcnew System::String(u8"\uf043"); }
    System::String^ ICON_FA::HAND_PEACE::get() { return gcnew System::String(u8"\uf25b"); }
    System::String^ ICON_FA::ALIGN_RIGHT::get() { return gcnew System::String(u8"\uf038"); }
    System::String^ ICON_FA::QUOTE_RIGHT::get() { return gcnew System::String(u8"\uf10e"); }
    System::String^ ICON_FA::BEER::get() { return gcnew System::String(u8"\uf0fc"); }
    System::String^ ICON_FA::FIRST_AID::get() { return gcnew System::String(u8"\uf479"); }
    System::String^ ICON_FA::ERASER::get() { return gcnew System::String(u8"\uf12d"); }
    System::String^ ICON_FA::SQUARE_FULL::get() { return gcnew System::String(u8"\uf45c"); }
    System::String^ ICON_FA::DOLLY::get() { return gcnew System::String(u8"\uf472"); }
    System::String^ ICON_FA::HAND_HOLDING::get() { return gcnew System::String(u8"\uf4bd"); }
    System::String^ ICON_FA::HOURGLASS_START::get() { return gcnew System::String(u8"\uf251"); }
    System::String^ ICON_FA::FAST_BACKWARD::get() { return gcnew System::String(u8"\uf049"); }
    System::String^ ICON_FA::FIRE::get() { return gcnew System::String(u8"\uf06d"); }
    System::String^ ICON_FA::FAST_FORWARD::get() { return gcnew System::String(u8"\uf050"); }
    System::String^ ICON_FA::VENUS_DOUBLE::get() { return gcnew System::String(u8"\uf226"); }
    System::String^ ICON_FA::VENUS::get() { return gcnew System::String(u8"\uf221"); }
    System::String^ ICON_FA::HASHTAG::get() { return gcnew System::String(u8"\uf292"); }
    System::String^ ICON_FA::SMOKING::get() { return gcnew System::String(u8"\uf48d"); }
    System::String^ ICON_FA::PENCIL_ALT::get() { return gcnew System::String(u8"\uf303"); }
    System::String^ ICON_FA::TRUCK_LOADING::get() { return gcnew System::String(u8"\uf4de"); }
    System::String^ ICON_FA::EXPAND_ARROWS_ALT::get() { return gcnew System::String(u8"\uf31e"); }
    System::String^ ICON_FA::CARET_SQUARE_DOWN::get() { return gcnew System::String(u8"\uf150"); }
    System::String^ ICON_FA::HDD::get() { return gcnew System::String(u8"\uf0a0"); }
    System::String^ ICON_FA::OBJECT_GROUP::get() { return gcnew System::String(u8"\uf247"); }
    System::String^ ICON_FA::NEWSPAPER::get() { return gcnew System::String(u8"\uf1ea"); }
    System::String^ ICON_FA::HOSPITAL_ALT::get() { return gcnew System::String(u8"\uf47d"); }
    System::String^ ICON_FA::ANCHOR::get() { return gcnew System::String(u8"\uf13d"); }
    System::String^ ICON_FA::HAND_POINT_LEFT::get() { return gcnew System::String(u8"\uf0a5"); }
    System::String^ ICON_FA::USER_TIMES::get() { return gcnew System::String(u8"\uf235"); }
    System::String^ ICON_FA::CALCULATOR::get() { return gcnew System::String(u8"\uf1ec"); }
    System::String^ ICON_FA::ENVELOPE_SQUARE::get() { return gcnew System::String(u8"\uf199"); }
    System::String^ ICON_FA::FILE_MEDICAL::get() { return gcnew System::String(u8"\uf477"); }
    System::String^ ICON_FA::GENDERLESS::get() { return gcnew System::String(u8"\uf22d"); }
    System::String^ ICON_FA::UNLOCK_ALT::get() { return gcnew System::String(u8"\uf13e"); }
    System::String^ ICON_FA::PAW::get() { return gcnew System::String(u8"\uf1b0"); }
    System::String^ ICON_FA::HAND_HOLDING_HEART::get() { return gcnew System::String(u8"\uf4be"); }
    System::String^ ICON_FA::ARCHIVE::get() { return gcnew System::String(u8"\uf187"); }
    System::String^ ICON_FA::PHONE_VOLUME::get() { return gcnew System::String(u8"\uf2a0"); }
    System::String^ ICON_FA::CARET_RIGHT::get() { return gcnew System::String(u8"\uf0da"); }
    System::String^ ICON_FA::HAND_POINT_DOWN::get() { return gcnew System::String(u8"\uf0a7"); }
    System::String^ ICON_FA::MAP_MARKER::get() { return gcnew System::String(u8"\uf041"); }
    System::String^ ICON_FA::CALENDAR_ALT::get() { return gcnew System::String(u8"\uf073"); }
    System::String^ ICON_FA::MICROPHONE::get() { return gcnew System::String(u8"\uf130"); }
    System::String^ ICON_FA::AMERICAN_SIGN_LANGUAGE_INTERPRETING::get() { return gcnew System::String(u8"\uf2a3"); }
    System::String^ ICON_FA::BINOCULARS::get() { return gcnew System::String(u8"\uf1e5"); }
    System::String^ ICON_FA::STICKY_NOTE::get() { return gcnew System::String(u8"\uf249"); }
    System::String^ ICON_FA::USER::get() { return gcnew System::String(u8"\uf007"); }
    System::String^ ICON_FA::EXPAND::get() { return gcnew System::String(u8"\uf065"); }
    System::String^ ICON_FA::MINUS_CIRCLE::get() { return gcnew System::String(u8"\uf056"); }
    System::String^ ICON_FA::CHESS_PAWN::get() { return gcnew System::String(u8"\uf443"); }
    System::String^ ICON_FA::CALENDAR_MINUS::get() { return gcnew System::String(u8"\uf272"); }
    System::String^ ICON_FA::SLIDERS_H::get() { return gcnew System::String(u8"\uf1de"); }
    System::String^ ICON_FA::CHESS_BOARD::get() { return gcnew System::String(u8"\uf43c"); }
    System::String^ ICON_FA::BIRTHDAY_CAKE::get() { return gcnew System::String(u8"\uf1fd"); }
    System::String^ ICON_FA::GOLF_BALL::get() { return gcnew System::String(u8"\uf450"); }
    System::String^ ICON_FA::CHART_BAR::get() { return gcnew System::String(u8"\uf080"); }
    System::String^ ICON_FA::TAXI::get() { return gcnew System::String(u8"\uf1ba"); }
    System::String^ ICON_FA::COMMENT::get() { return gcnew System::String(u8"\uf075"); }
    System::String^ ICON_FA::ROCKET::get() { return gcnew System::String(u8"\uf135"); }
    System::String^ ICON_FA::HANDS::get() { return gcnew System::String(u8"\uf4c2"); }
    System::String^ ICON_FA::ARROWS_ALT::get() { return gcnew System::String(u8"\uf0b2"); }
    System::String^ ICON_FA::FILE_WORD::get() { return gcnew System::String(u8"\uf1c2"); }
    System::String^ ICON_FA::THERMOMETER_EMPTY::get() { return gcnew System::String(u8"\uf2cb"); }
    System::String^ ICON_FA::USER_CIRCLE::get() { return gcnew System::String(u8"\uf2bd"); }
    System::String^ ICON_FA::HANDSHAKE::get() { return gcnew System::String(u8"\uf2b5"); }
    System::String^ ICON_FA::CUT::get() { return gcnew System::String(u8"\uf0c4"); }
    System::String^ ICON_FA::STREET_VIEW::get() { return gcnew System::String(u8"\uf21d"); }
    System::String^ ICON_FA::ARROW_CIRCLE_UP::get() { return gcnew System::String(u8"\uf0aa"); }
    System::String^ ICON_FA::BASKETBALL_BALL::get() { return gcnew System::String(u8"\uf434"); }
    System::String^ ICON_FA::DESKTOP::get() { return gcnew System::String(u8"\uf108"); }
    System::String^ ICON_FA::SPINNER::get() { return gcnew System::String(u8"\uf110"); }
    System::String^ ICON_FA::TOGGLE_ON::get() { return gcnew System::String(u8"\uf205"); }
    System::String^ ICON_FA::MINUS_SQUARE::get() { return gcnew System::String(u8"\uf146"); }
    System::String^ ICON_FA::STOPWATCH::get() { return gcnew System::String(u8"\uf2f2"); }
    System::String^ ICON_FA::ARROW_ALT_CIRCLE_LEFT::get() { return gcnew System::String(u8"\uf359"); }
    System::String^ ICON_FA::SAVE::get() { return gcnew System::String(u8"\uf0c7"); }
    System::String^ ICON_FA::TRASH_ALT::get() { return gcnew System::String(u8"\uf2ed"); }
    System::String^ ICON_FA::PUZZLE_PIECE::get() { return gcnew System::String(u8"\uf12e"); }
    System::String^ ICON_FA::EXTERNAL_LINK_ALT::get() { return gcnew System::String(u8"\uf35d"); }
    System::String^ ICON_FA::FROWN::get() { return gcnew System::String(u8"\uf119"); }
    System::String^ ICON_FA::SIGN_LANGUAGE::get() { return gcnew System::String(u8"\uf2a7"); }
    System::String^ ICON_FA::FILE_MEDICAL_ALT::get() { return gcnew System::String(u8"\uf478"); }
    System::String^ ICON_FA::ARROW_LEFT::get() { return gcnew System::String(u8"\uf060"); }
    System::String^ ICON_FA::BOXES::get() { return gcnew System::String(u8"\uf468"); }
    System::String^ ICON_FA::HAND_POINTER::get() { return gcnew System::String(u8"\uf25a"); }
    System::String^ ICON_FA::PLUS_SQUARE::get() { return gcnew System::String(u8"\uf0fe"); }
    System::String^ ICON_FA::EXCLAMATION_TRIANGLE::get() { return gcnew System::String(u8"\uf071"); }
    System::String^ ICON_FA::GIFT::get() { return gcnew System::String(u8"\uf06b"); }
    System::String^ ICON_FA::COGS::get() { return gcnew System::String(u8"\uf085"); }
    System::String^ ICON_FA::SIGNAL::get() { return gcnew System::String(u8"\uf012"); }
    System::String^ ICON_FA::ARROW_UP::get() { return gcnew System::String(u8"\uf062"); }
    System::String^ ICON_FA::SERVER::get() { return gcnew System::String(u8"\uf233"); }
    System::String^ ICON_FA::BATTERY_EMPTY::get() { return gcnew System::String(u8"\uf244"); }
    System::String^ ICON_FA::CHEVRON_CIRCLE_LEFT::get() { return gcnew System::String(u8"\uf137"); }
    System::String^ ICON_FA::SITEMAP::get() { return gcnew System::String(u8"\uf0e8"); }
    System::String^ ICON_FA::ID_BADGE::get() { return gcnew System::String(u8"\uf2c1"); }
    System::String^ ICON_FA::FILE_CODE::get() { return gcnew System::String(u8"\uf1c9"); }
    System::String^ ICON_FA::BOWLING_BALL::get() { return gcnew System::String(u8"\uf436"); }
    System::String^ ICON_FA::TERMINAL::get() { return gcnew System::String(u8"\uf120"); }
    System::String^ ICON_FA::BATTERY_FULL::get() { return gcnew System::String(u8"\uf240"); }
    System::String^ ICON_FA::DEAF::get() { return gcnew System::String(u8"\uf2a4"); }
    System::String^ ICON_FA::WINDOW_MINIMIZE::get() { return gcnew System::String(u8"\uf2d1"); }
    System::String^ ICON_FA::MARS_DOUBLE::get() { return gcnew System::String(u8"\uf227"); }
    System::String^ ICON_FA::EXCHANGE_ALT::get() { return gcnew System::String(u8"\uf362"); }
    System::String^ ICON_FA::HOME::get() { return gcnew System::String(u8"\uf015"); }
    System::String^ ICON_FA::COMMENT_ALT::get() { return gcnew System::String(u8"\uf27a"); }
    System::String^ ICON_FA::SEARCH_MINUS::get() { return gcnew System::String(u8"\uf010"); }
    System::String^ ICON_FA::UTENSIL_SPOON::get() { return gcnew System::String(u8"\uf2e5"); }
    System::String^ ICON_FA::QUIDDITCH::get() { return gcnew System::String(u8"\uf458"); }
    System::String^ ICON_FA::EXCLAMATION_CIRCLE::get() { return gcnew System::String(u8"\uf06a"); }
    System::String^ ICON_FA::COMMENTS::get() { return gcnew System::String(u8"\uf086"); }
    System::String^ ICON_FA::MOON::get() { return gcnew System::String(u8"\uf186"); }
    System::String^ ICON_FA::CARET_SQUARE_RIGHT::get() { return gcnew System::String(u8"\uf152"); }
    System::String^ ICON_FA::CHART_PIE::get() { return gcnew System::String(u8"\uf200"); }
    System::String^ ICON_FA::BOLD::get() { return gcnew System::String(u8"\uf032"); }
    System::String^ ICON_FA::BARCODE::get() { return gcnew System::String(u8"\uf02a"); }
    System::String^ ICON_FA::HANDS_HELPING::get() { return gcnew System::String(u8"\uf4c4"); }
    System::String^ ICON_FA::BOLT::get() { return gcnew System::String(u8"\uf0e7"); }
    System::String^ ICON_FA::THERMOMETER_QUARTER::get() { return gcnew System::String(u8"\uf2ca"); }
    System::String^ ICON_FA::DNA::get() { return gcnew System::String(u8"\uf471"); }
    System::String^ ICON_FA::TROPHY::get() { return gcnew System::String(u8"\uf091"); }
    System::String^ ICON_FA::BRAILLE::get() { return gcnew System::String(u8"\uf2a1"); }
    System::String^ ICON_FA::INDUSTRY::get() { return gcnew System::String(u8"\uf275"); }
    System::String^ ICON_FA::CLOUD_DOWNLOAD_ALT::get() { return gcnew System::String(u8"\uf381"); }
    System::String^ ICON_FA::PLUS::get() { return gcnew System::String(u8"\uf067"); }
    System::String^ ICON_FA::LIST_UL::get() { return gcnew System::String(u8"\uf0ca"); }
    System::String^ ICON_FA::ROAD::get() { return gcnew System::String(u8"\uf018"); }
    System::String^ ICON_FA::VOLUME_DOWN::get() { return gcnew System::String(u8"\uf027"); }
    System::String^ ICON_FA::QUESTION_CIRCLE::get() { return gcnew System::String(u8"\uf059"); }
    System::String^ ICON_FA::TRADEMARK::get() { return gcnew System::String(u8"\uf25c"); }
    System::String^ ICON_FA::IMAGE::get() { return gcnew System::String(u8"\uf03e"); }
    System::String^ ICON_FA::CHILD::get() { return gcnew System::String(u8"\uf1ae"); }
    System::String^ ICON_FA::ANGLE_DOUBLE_RIGHT::get() { return gcnew System::String(u8"\uf101"); }
    System::String^ ICON_FA::BATH::get() { return gcnew System::String(u8"\uf2cd"); }
    System::String^ ICON_FA::REPLY_ALL::get() { return gcnew System::String(u8"\uf122"); }
    System::String^ ICON_FA::FEMALE::get() { return gcnew System::String(u8"\uf182"); }
    System::String^ ICON_FA::SYRINGE::get() { return gcnew System::String(u8"\uf48e"); }
    System::String^ ICON_FA::CIRCLE_NOTCH::get() { return gcnew System::String(u8"\uf1ce"); }
    System::String^ ICON_FA::CARET_SQUARE_LEFT::get() { return gcnew System::String(u8"\uf191"); }
    System::String^ ICON_FA::WEIGHT::get() { return gcnew System::String(u8"\uf496"); }
    System::String^ ICON_FA::SHARE_SQUARE::get() { return gcnew System::String(u8"\uf14d"); }
    System::String^ ICON_FA::TABLE_TENNIS::get() { return gcnew System::String(u8"\uf45d"); }
    System::String^ ICON_FA::THERMOMETER_HALF::get() { return gcnew System::String(u8"\uf2c9"); }
    System::String^ ICON_FA::QUESTION::get() { return gcnew System::String(u8"\uf128"); }
    System::String^ ICON_FA::VIALS::get() { return gcnew System::String(u8"\uf493"); }
    System::String^ ICON_FA::LOW_VISION::get() { return gcnew System::String(u8"\uf2a8"); }
    System::String^ ICON_FA::SHIPPING_FAST::get() { return gcnew System::String(u8"\uf48b"); }
    System::String^ ICON_FA::ITALIC::get() { return gcnew System::String(u8"\uf033"); }
    System::String^ ICON_FA::FORWARD::get() { return gcnew System::String(u8"\uf04e"); }
    System::String^ ICON_FA::GLOBE::get() { return gcnew System::String(u8"\uf0ac"); }
    System::String^ ICON_FA::THUMBS_DOWN::get() { return gcnew System::String(u8"\uf165"); }
    System::String^ ICON_FA::CHEVRON_RIGHT::get() { return gcnew System::String(u8"\uf054"); }
    System::String^ ICON_FA::TACHOMETER_ALT::get() { return gcnew System::String(u8"\uf3fd"); }
    System::String^ ICON_FA::BUS::get() { return gcnew System::String(u8"\uf207"); }
    System::String^ ICON_FA::REGISTERED::get() { return gcnew System::String(u8"\uf25d"); }
    System::String^ ICON_FA::ANGLE_DOWN::get() { return gcnew System::String(u8"\uf107"); }
    System::String^ ICON_FA::HAND_ROCK::get() { return gcnew System::String(u8"\uf255"); }
    System::String^ ICON_FA::WINDOW_CLOSE::get() { return gcnew System::String(u8"\uf410"); }
    System::String^ ICON_FA::LINK::get() { return gcnew System::String(u8"\uf0c1"); }
    System::String^ ICON_FA::PODCAST::get() { return gcnew System::String(u8"\uf2ce"); }
    System::String^ ICON_FA::TRUCK_MOVING::get() { return gcnew System::String(u8"\uf4df"); }
    System::String^ ICON_FA::BUG::get() { return gcnew System::String(u8"\uf188"); }
    System::String^ ICON_FA::SHIELD_ALT::get() { return gcnew System::String(u8"\uf3ed"); }
    System::String^ ICON_FA::INFO::get() { return gcnew System::String(u8"\uf129"); }
    System::String^ ICON_FA::CHESS_KING::get() { return gcnew System::String(u8"\uf43f"); }
    System::String^ ICON_FA::NEUTER::get() { return gcnew System::String(u8"\uf22c"); }
    System::String^ ICON_FA::PAINT_BRUSH::get() { return gcnew System::String(u8"\uf1fc"); }
    System::String^ ICON_FA::COMMENT_SLASH::get() { return gcnew System::String(u8"\uf4b3"); }
    System::String^ ICON_FA::SUITCASE::get() { return gcnew System::String(u8"\uf0f2"); }
    System::String^ ICON_FA::HOSPITAL_SYMBOL::get() { return gcnew System::String(u8"\uf47e"); }
    System::String^ ICON_FA::X_RAY::get() { return gcnew System::String(u8"\uf497"); }
    System::String^ ICON_FA::DOT_CIRCLE::get() { return gcnew System::String(u8"\uf192"); }
    System::String^ ICON_FA::VENUS_MARS::get() { return gcnew System::String(u8"\uf228"); }
    System::String^ ICON_FA::PAUSE_CIRCLE::get() { return gcnew System::String(u8"\uf28b"); }
    System::String^ ICON_FA::SORT_NUMERIC_DOWN::get() { return gcnew System::String(u8"\uf162"); }
    System::String^ ICON_FA::TH_LARGE::get() { return gcnew System::String(u8"\uf009"); }
    System::String^ ICON_FA::AT::get() { return gcnew System::String(u8"\uf1fa"); }
    System::String^ ICON_FA::FILE::get() { return gcnew System::String(u8"\uf15b"); }
    System::String^ ICON_FA::STAR_HALF::get() { return gcnew System::String(u8"\uf089"); }
    System::String^ ICON_FA::FLAG_CHECKERED::get() { return gcnew System::String(u8"\uf11e"); }
    System::String^ ICON_FA::SHIP::get() { return gcnew System::String(u8"\uf21a"); }
    System::String^ ICON_FA::CHECK::get() { return gcnew System::String(u8"\uf00c"); }
    System::String^ ICON_FA::FILM::get() { return gcnew System::String(u8"\uf008"); }
    System::String^ ICON_FA::LEMON::get() { return gcnew System::String(u8"\uf094"); }
    System::String^ ICON_FA::PERCENT::get() { return gcnew System::String(u8"\uf295"); }
    System::String^ ICON_FA::BOOK::get() { return gcnew System::String(u8"\uf02d"); }
    System::String^ ICON_FA::THERMOMETER_THREE_QUARTERS::get() { return gcnew System::String(u8"\uf2c8"); }
    System::String^ ICON_FA::WAREHOUSE::get() { return gcnew System::String(u8"\uf494"); }
    System::String^ ICON_FA::TRANSGENDER::get() { return gcnew System::String(u8"\uf224"); }
    System::String^ ICON_FA::TRASH::get() { return gcnew System::String(u8"\uf1f8"); }
    System::String^ ICON_FA::FILE_AUDIO::get() { return gcnew System::String(u8"\uf1c7"); }
    System::String^ ICON_FA::LIRA_SIGN::get() { return gcnew System::String(u8"\uf195"); }
    System::String^ ICON_FA::STAR::get() { return gcnew System::String(u8"\uf005"); }
    System::String^ ICON_FA::USERS::get() { return gcnew System::String(u8"\uf0c0"); }
    System::String^ ICON_FA::TRANSGENDER_ALT::get() { return gcnew System::String(u8"\uf225"); }
    System::String^ ICON_FA::ASTERISK::get() { return gcnew System::String(u8"\uf069"); }
    System::String^ ICON_FA::PLUS_CIRCLE::get() { return gcnew System::String(u8"\uf055"); }
    System::String^ ICON_FA::CART_ARROW_DOWN::get() { return gcnew System::String(u8"\uf218"); }
    System::String^ ICON_FA::HAND_SCISSORS::get() { return gcnew System::String(u8"\uf257"); }
    System::String^ ICON_FA::LEAF::get() { return gcnew System::String(u8"\uf06c"); }
    System::String^ ICON_FA::BUILDING::get() { return gcnew System::String(u8"\uf1ad"); }
    System::String^ ICON_FA::PRESCRIPTION_BOTTLE_ALT::get() { return gcnew System::String(u8"\uf486"); }
    System::String^ ICON_FA::PEOPLE_CARRY::get() { return gcnew System::String(u8"\uf4ce"); }
    System::String^ ICON_FA::BAND_AID::get() { return gcnew System::String(u8"\uf462"); }
    System::String^ ICON_FA::WIFI::get() { return gcnew System::String(u8"\uf1eb"); }
    System::String^ ICON_FA::LONG_ARROW_ALT_DOWN::get() { return gcnew System::String(u8"\uf309"); }
    System::String^ ICON_FA::ANGLE_DOUBLE_DOWN::get() { return gcnew System::String(u8"\uf103"); }
    System::String^ ICON_FA::CHEVRON_UP::get() { return gcnew System::String(u8"\uf077"); }
    System::String^ ICON_FA::HAND_SPOCK::get() { return gcnew System::String(u8"\uf259"); }
    System::String^ ICON_FA::STETHOSCOPE::get() { return gcnew System::String(u8"\uf0f1"); }
    System::String^ ICON_FA::BACKWARD::get() { return gcnew System::String(u8"\uf04a"); }
    System::String^ ICON_FA::HAND_POINT_UP::get() { return gcnew System::String(u8"\uf0a6"); }

}